job_strategies:
  daikon.no_retry:
    class: Daikon\AsyncJob\Strategy\JobStrategy
    retry:
      class: Daikon\AsyncJob\Strategy\Retry\NoRetry
    failure:
      class: Daikon\AsyncJob\Strategy\Retry\NoRetry

job_workers:
  daikon.message_queue:
    class: Daikon\RabbitMq3\Job\RabbitMq3Worker
    dependencies:
      connector: daikon.message_queue
